### ISSUE TITLE
New created map is unable to load 

### ISSUE THREAD

**Issue by RahaAkhtar** [Ubudu/IOS-IndoorLocation-SDK#1]
Hi  Jean Felix TRAN,
How are you?

I have create a new venue from your (https://manager.ubudu.com/) ubudu manager.For testing purpose i have added a map as per your given instruction. I get the new map key when i successfully create a map.
I'm using your demo application and i replaced the map keys, but unfortunately new added map is not able to view in UBUMapViewController and your already given map is working fine.

"NSString *mapKey = mapKeys;
    [self.locationManager loadMapWithKey:mapKey success:^{
        NSLog(@"Map loading success");

```
    [self.locationManager start];
    [self.showMapButton setEnabled:YES];

} failure:^(NSError *error) {
    NSLog(@"Map loading failure: %@", error);

    [self displayError:error];
    [self.showMapButton setEnabled:NO];
}];
```

"
In log i always getting "Map loading success".
Your help can be appreciated. 

Best Regards,
Akhtar

**Comment by zioolek** [comment]
Hi Akhtar,

Before I can answer - Could you share your map UUID with me? I will try to reproduce your bug and then check where the problem is…

Beast Regards,
Tom
