### ISSUE TITLE
Upload image not display 

### ISSUE THREAD

**Issue by bhushanpawar07** [Ubudu/IOS-IndoorLocation-SDK#2]
Hello team ,
indoor map not display in demo app 

 [self.locationManager loadApplicationForNamespace:namespace
                                       downloadImages:YES
                                              success:^{
                                                  NSLog(@"We've loaded application for namespace: %@", namespace);
                                                  
                                                  NSError *error = nil;
                                                  BOOL started = [_locationManager start:&error];
                                                  if (error == nil && started == YES) {
                                                      
                                                      NSString *template = @"https://imagesd.ubudu.com/u_maps_tiles/87444/9903848c8e9299a6d851adedd626988d/{z}/{x}/{y}.png";
                                                      MKTileOverlay *overLay = [[MKTileOverlay alloc] initWithURLTemplate:template];
                                                      overLay.canReplaceMapContent = YES;
                                                      
                                                      [self.mapView addOverlay:overLay level:MKOverlayLevelAboveLabels];
                                                      [self.mapView setRegion:MKCoordinateRegionMake(CLLocationCoordinate2DMake(23.0269, 72.5241), MKCoordinateSpanMake(0.25, 0.25))];
                                                      
                                                    
                                                      NSLog(@"location manager started %@",_locationManager.mapOverlayForCurrentMap);
                                                      
                                                      
                                                  }
                                                  else { NSLog(@"error while starting IL manager: %@", error); }
                                                  
                                              } failure:^(NSError *error) {
                                                  NSLog(@"Error while loading application for namespace: %@", error.localizedDescription);
                                              }];
    
}

 [self.locationManager loadApplicationForNamespace:namespace
                                       downloadImages:YES

Map image not display

**Comment by zioolek** [comment]
Try to load your map (set proper namespace). The map image should display after detecting a beacon from that map...

**Comment by everardotrejog** [comment]
Hi, I have an issue with the demo that is published for inddorlocation.

The Demo version Ubudu / IOS-IndoorLocation-SDK not view the image configurate at console


NSString *namespace = @"2922b5a5da2ee43a943b74e3620ccbc8f8872d5c";
    
    self.locationManager = [UBUIndoorLocationManager sharedInstance];
    self.locationManager.delegate = self;

    UBUIndoorLocationConfiguration *ilConfig = [[UBUIndoorLocationConfiguration alloc] initWithAppNamespace:namespace];
    ilConfig.motionFiltering = YES;
    ilConfig.updateHeading = YES;
    ilConfig.localizationMode = kBLEMode;
   
    self.locationManager.configuration = ilConfig;
    [self.locationManager startWithCompletionBlock:^(NSError *error) {
        
        if(error != nil) {
            NSLog(@"Error while loading application for namespace: %@", error.localizedDescription);
            return;
        }
     
        NSLog(@"location manager started");
    }];


And the version example of version v2.7.0 

Tampoco muestra la imagen configurada. 
  self.locationManager = [UBUIndoorLocationManager sharedInstance];
    self.locationManager.delegate = self;
    self.locationManager.motionFiltering = YES;
    self.locationManager.updateHeading = YES;
    
    [self.locationManager loadApplicationForNamespace:namespace
                                       downloadImages:YES
                                              success:^{
                                                  NSLog(@"We've loaded application for namespace: %@", namespace);
                                                  
                                                  NSError *error = nil;
                                                  BOOL started = [_locationManager start:&error];
                                                  if (error == nil && started == YES) { NSLog(@"location manager started"); }
                                                  else { NSLog(@"error while starting IL manager: %@", error); }
                                                  
                                              } failure:^(NSError *error) {
                                                  NSLog(@"Error while loading application for namespace: %@", error.localizedDescription);
                                              }];


When run first not show the image map. 

And next run every crashing

Assertion failure in -[CLLocationManager startRangingBeaconsInRegion:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/CoreLocationFramework/CoreLocation-2245.0.41/Framework/CoreLocation/CLLocationManager.m:1283

as a note, on Android with the same key show the image map and iOS do not show the image map 

My key is 2922b5a5da2ee43a943b74e3620ccbc8f8872d5c.

**Comment by zioolek** [comment]
everardotrejog please check my reply here: https://github.com/Ubudu/IOS-IndoorLocation-SDK/issues/3
